config/routes.rb
Rails.application.routes.draw do
  root to: 'tops#index'
  resources :tasks
  namespace :admin do
    resources :users
  end
  resources :users
  resources :sessions, only: %i[new create destroy]
  resources :labels
  resources :groups
  resources :assigns, only: %i[create destroy]

  mount LetterOpenerWeb::Engine, at: "/letter_opener"

end

app/models/label.rb
class Label < ApplicationRecord

  has_many :favorites, dependent: :destroy

  has_many :favorite_tasks, through: :favorites, source: :task

  belongs_to :user

  validates :content, presence: true, uniqueness: true
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :admin_allow
  
  def index
    @labels = Label.all
  end

  def new
    @label = Label.new
  end

  def create
    @label = current_user.labels.build(set_params)
    if @label.save
      flash[:success] = "ラベルを作成しました"
      redirect_to labels_path
    else
      flash.now[:danger] = "もう一度入力をして下さい"
      render 'new'
    end
  end

  def destroy
    @label = Label.find(params[:id])
    @label.destroy
    flash[:info] = "ラベルを削除しました"
    redirect_to labels_path
  end

  private
  def set_params
    params.require(:label).permit(:content, :task_id, :user_id)

  end

  def admin_allow
    unless current_user.try(:admin?)
      flash[:danger] = "権限がありません"
      redirect_to tasks_path
    end
  end

end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/views/labels/index.html.erb
<div class="x-scroll">
<table class="table">
  <thead>
    <tr>
      <th>ラベル名</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @labels.each do |l| %>
      <tr>
        <td><%= l.content %></td>
        <td><%= link_to "削除", label_path(l), method: :delete, data: {confirm: "削除して宜しいですか？"} %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
&nbsp
<%= link_to "ラベルを作成する", new_label_path %>

app/views/labels/new.html.erb
<h1>ラベルの作成</h1>

<%= form_with(model: @label,local: true) do |f| %>
  <% if @label.errors.any? %>
    <div id="error_explanation">
      <h2><%= @label.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @label.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :content, "ラベル名" %>
    <%= f.text_field :content,  class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit "作成する" %>
  </div>
  <div class="form-group">
    <%= link_to "戻る", labels_path %>
  </div>
<% end %>