config/routes.rb
Rails.application.routes.draw do
  root to: 'tops#index'
  resources :tasks
  namespace :admin do
    resources :users
  end
  resources :users
  resources :sessions, only: %i[new create destroy]
  resources :labels
  resources :groups
  resources :assigns, only: %i[create destroy]

  mount LetterOpenerWeb::Engine, at: "/letter_opener"

end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :owner, class_name: 'User', foreign_key: :owner_id
  has_many :assigns, dependent: :destroy

  # あるグループに紐づくuser一覧を取得
  has_many :group_users, through: :assigns, source: :user
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :find_params, only: %i[show edit update destroy]
  before_action :update_or_delete, only: %i[edit update destroy]
  before_action :allow_show, only: %i[show]

  def index
    @groups = Group.all
  end

  def new
    @group =Group.new
  end

  def create
    @group = Group.new(set_params)
    @group.owner = current_user
    if @group.save
      # グループ作成と同時に、グループに参加する
      current_user.assigns.create(group_id: @group.id, leader: true)
      # @group.invite_member(@group.owner)
      flash[:success] = "グループを作成しました"
      redirect_to groups_path
    else
      flash.now[:danger] = "もう一度入力をして下さい"
      render 'new'
    end
  end

  def show
    user = @group.group_users.pluck(:id)
    @tasks = Task.where(user_id: user)
  end

  def edit; end

  def update
    if @group.update(set_params)
      flash[:success] = "グループを更新しました"
      redirect_to groups_path
    else
      flash.now[:error] = "もう一度入力をして下さい"
      render :edit
    end
  end

  def destroy
    @group.destroy
    flash[:info] = "グループを削除しました"
    redirect_to groups_path

  end

  private

  def set_params
    params.require(:group).permit(:name, :content)
  end

  def find_params
    @group = Group.find(params[:id])
  end

  def update_or_delete
    unless current_user.id == @group.owner_id
      flash[:info] = "権限がありません"
      redirect_to groups_path
    end
  end

  def allow_show
    unless current_user.id == @group.assigns.where(user_id: current_user.id).pluck(:user_id)[0]
      flash[:info] = "権限がありません"
      redirect_to groups_path
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: @group,local: true) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= @group.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, "グループ名" %>
    <%= f.text_field :name,  class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :content, "グループの説明" %>
    <%= f.text_area :content, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "作成する" %>
  </div>
  <div class="form-group">
    <%= link_to "戻る", tasks_path %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>グループ編集</h1>

<%= render 'form' %>

app/views/groups/index.html.erb
<h1>グループ一覧</h1>

<div class="x-scroll">
<table class="table">
  <thead>
    <tr>
      <th>グループ名</th>
      <th>グループの説明</th>
      <th></th>
      <th></th> 
      <th></th> 
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= group.content %></td>
        <% if group.assigns.pluck(:user_id).include?current_user.id %>
          <td><%= link_to "詳細", group_path(group) %>
        <% end %>
        <% if current_user.id == group.owner_id %>
          <td><%= link_to "編集", edit_group_path(group) %> <!-- グループのownerのみ -->
          <td><%= link_to "削除", group_path(group), 
          method: :delete, data: {confirm: "削除して宜しいですか？"} %></td> <!-- グループのownerのみ -->
        <% end %>
        <% if !group.assigns.pluck(:user_id).include?current_user.id %>
          <td><%= link_to "参加", assigns_path(group_id: group.id), method: :post %></td>
        <% end %>

        <% if group.assigns.pluck(:user_id).include?current_user.id %>
          <% unless group.assigns.where(user_id: current_user.id).find_by(leader: true) %>
            <td><%= link_to "脱退", assign_path(id: current_user.assigns.pluck(:id)),method: :delete, data: {confirm: "退会してよろしいですか？"} %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
  &nbsp
<div>
  <%= link_to "グループを作成する", new_group_path %>
</div>
  &nbsp
<div>
  <%= link_to "戻る", tasks_path %>
</div>

app/views/groups/new.html.erb
<h1>グループ作成</h1>

<%= render 'form' %>

app/views/groups/show.html.erb
<h1>グループの詳細</h1>

<div class="x-scroll">
  <table class="table table-bordered text-center">
    <tr>
      <th>グループ名</th>
      <td><%= @group.name %></td>
    <tr>
    <tr>
      <th>詳細</th>
      <td><%= @group.content %></td>
    </tr>
  </table>
</div>
&nbsp
&nbsp
<h1><%= @group.name%>のユーザーが持つタスク一覧</h1>

<div class="x-scroll">
  <table class="table">
  <thead>
    <tr>
      <th>タスク名</th>
      <th>ユーザー名</th>
      <th>詳細</th>
      <th>終了期限</th>
      <th>状態</th>
      <th>優先順位</th>
      <th class="text-center">ラベル</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td class="task_title"><%= task.title %></td>
        <td><%= task.content %></td>
        <td><%= task.user.name %></td>
        <td><%= task.deadline.strftime("%Y年%m月%d日")%></td>
        <td><%= task.status %></td>
        <td class="text-center"><%= task.priority_i18n %>
        <td>
          <% task.favorites_labels.each do |l| %>
          <ul>
            <li><%= l.content %></li>
          </ul>
           <% end %>
        </td>
        <td class="task_show"><%= link_to "詳細", task_path(task, r: task.id) %></td>
        <td><%= task.reads.find_by(user_id: current_user.id) ? '既読' : '未読' %></td>
      </tr>
    <% end %>
  </tbody>

  </table>
</div>
<div>
  <%= link_to "戻る", groups_path %>
</div>