config/routes.rb
Rails.application.routes.draw do
  root to: 'tops#index'
  resources :tasks
  namespace :admin do
    resources :users
  end
  resources :users
  resources :sessions, only: %i[new create destroy]
  resources :labels
  resources :groups
  resources :assigns, only: %i[create destroy]

  mount LetterOpenerWeb::Engine, at: "/letter_opener"

end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: {maximum: 50}
  validates :email, presence: true, length: {maximum: 255},
    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
    uniqueness: true
  validates :password, presence: true, length: {minimum: 5}
  before_save { email.downcase! }
  has_secure_password
  has_many :tasks, dependent: :destroy
  has_many :labels

  # オーナを抽出
  has_many :groups, foreign_key: :owner_id
  has_many :assigns, dependent: :destroy
  
  # 入っているグループ全部を紐付ける
  has_many :groups, through: :assigns

  before_destroy :delete_admin

  has_many :reads, dependent: :destroy

  has_one_attached :image

  # private

  # def delete_admin
  #   if User.where(admin: true).count <= 1
  #      flash[:danger] = "管理者を居なくなってしまうため、削除できません"
  #      redirect_to tasks_path
  #   end
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :user_admin?
  before_action :user_params, only: %i[show edit update destroy]
  before_action :delete_admin, only: %i[destroy]

  def index
    @users = User.select(:id,:name, :email, :admin).page(params[:page]).per(10)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(set_params)
    if @user.save
      flash[:success] = "ユーザー登録に成功しました"
      redirect_to admin_users_path
    else
      flash[:danger] = "ユーザ登録に失敗しました"
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user.destroy
    flash[:info] = "ユーザー情報を削除しました"
    redirect_to tasks_path
  end


  private

  def user_admin?
    unless current_user.try(:admin?)
      flash[:danger] = "アクセス権限がありません"
      redirect_to root_path
    end
  end

  def set_params
    params.require(:user).permit(:name,:email, :password, :password_confirmation)
  end

  def user_params
    @user = User.find(params[:id])
  end

  def delete_admin
    if User.where(admin: true).count <= 1
       flash[:danger] = "管理者を居なくなってしまうため、削除できません"
       redirect_to tasks_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :not_allow_new, only: %i[new]
  before_action :not_allow_show, only: %i[show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "アサインしました"
      redirect_to tasks_path
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @tasks = @user.tasks
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "ユーザー情報を更新しました"
      redirect_to  user_path(@user)
    else
      flash[:danger] = "ユーザー情報の更新に失敗しました"
      redirect_to  user_path(@user)
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin, :image)
  end

  def not_allow_new
    if logged_in?
      flash[:info] = "ログイン済みです"
      redirect_to tasks_path
    end
  end

  def not_allow_show
    @user = User.find(params[:id])
    unless current_user.try(:admin) || current_user.id == @user.id
      flash[:info] = "アクセスできません"
      redirect_to tasks_path
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>プロフィール編集</h1>

<%= form_with(model: @user, local: true) do |f| %>

<div class="form-group">
  <%= f.label :name, "名前" %>
  <%= f.text_field :name,class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :email, "メールアドレス" %>
  <%= f.email_field :email,class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :image, "プロフィール画像" %><br>
  <%= f.file_field :image %>
  <td><%= image_tag @user.image.variant(resize:'100x100').processed if @user.image.attached? %></td>
</div>

<div class="form-group">
  <%= f.label :password, "本人確認のためパスワードを入力してください" %>
  <%= f.password_field :password,class: "form-control" %>
</div>

<%= f.submit "登録する" %>
<% end %>

app/views/users/new.html.erb
<h1>新規登録</h1>

<%= form_with(model: @user, local: true) do |f| %>

<div class="form-group">
  <%= f.label :name, "名前" %>
  <%= f.text_field :name,class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :email, "メールアドレス" %>
  <%= f.email_field :email,class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :image, "プロフィール画像" %><br>
  <%= f.file_field :image %>
</div>
<div class="form-group">
  <%= f.label :password, "ご希望のパスワード" %>
  <%= f.password_field :password,class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :password_confirmation, "もう一度ご希望のパスワードを入力して下さい" %>
  <%= f.password_field :password_confirmation,class: "form-control" %>
</div>

<%= f.submit "登録する" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>さんの情報</h1>

<table class="table table-bordered text-center">

<tr>
  <th>プロフィール画像</th>
  <td><%= image_tag @user.image.variant(resize:'100x100').processed if @user.image.attached? %></td>
</tr>

<tr>
  <th>名前</th>
  <td><%= @user.name %></td>
<tr>
<tr>
  <th>メールアドレス</th>
  <td><%= @user.email %></td>
</tr>

<% if current_user.try(:admin?) %>
  <tr>
    <th>管理者権限の有無</th>
    <td><%= @user.admin ? "有り" : "無し" %></td>
  </tr>

<tr>
  <th></th>
  <td><%= link_to "編集", edit_admin_user_path(@user) %></td>
</tr>
<% end %>
</table>

<h3><%= link_to "プロフィール編集", edit_user_path(@user) %></h3>

<h2><%= @user.name %>さんのタスク一覧</h2>

<table class="table table-striped table-bordered text-center">
  <tr>
    <th>タスク名</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% @tasks.each do |task| %>
  <tr>
   <td><%= task.title %></td>
   <td><%= link_to "詳細", task_path(task.id) %></td>
   <td><%= link_to "編集", edit_task_path(task.id) %></td>
   <td><%= link_to "削除", task_path(task.id),method: :delete, data: {confirm: "削除して宜しいですか？"} %></td>
  </tr>

<% end %>
</table>