config/routes.rb
Rails.application.routes.draw do
  root to: 'tops#index'
  resources :tasks
  namespace :admin do
    resources :users
  end
  resources :users
  resources :sessions, only: %i[new create destroy]
  resources :labels
  resources :groups
  resources :assigns, only: %i[create destroy]

  mount LetterOpenerWeb::Engine, at: "/letter_opener"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManagementApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>
    <header class="fixed-top">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to "タスク管理アプリ", tasks_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <% if logged_in? %>
            <li class="nav-item active">
              <%= link_to "タスクを作成する", new_task_path, class: "nav-link" %>         
            </li>
            <li class="nav-item active">
              <%= link_to "#{current_user.name}さんの情報", user_path(current_user.id), class: "nav-link" %>         
            </li>
            <li class="nav-item active">
              <%= link_to "ログアウト", session_path(current_user.id), method: :delete,class: "nav-link" %>         
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          グループ関連
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "グループ一覧", groups_path, class: "nav-link" %>
                <%= link_to "グループ新規作成", new_group_path, class: "nav-link" %>  
              </div>
            </li>
          <% else %>
            <li class="nav-item active">
              <%= link_to "ユーザー登録", new_user_path, class: "nav-link" %>         
            </li>
            <li class="nav-item active">
              <%= link_to "ログイン", new_session_path, class: "nav-link" %>         
            </li>
          <% end %>
          <% if current_user.try(:admin?) %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          ユーザー関連
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "ユーザー一覧", admin_users_path, class: "nav-link" %> 
                <%= link_to "ユーザー新規作成", new_admin_user_path, class: "nav-link" %>  
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          ラベル関連
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "ラベル一覧", labels_path, class: "nav-link" %>
                <%= link_to "ラベル新規作成", new_label_path, class: "nav-link" %>  
              </div>
            </li>
          <% end %>


        </ul>
      </div>
    </nav>
  </header>
    <div class="container">
      <!-- flashメッセージの表示 -->
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
        <%= yield %>
    </div>
    <div class="container-fluid">
    <footer class="footer">
      <p>Powered by Aguru Itabashi</p>
    </footer>
    </div>
  </body>
</html>

app/views/layouts/top.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManagementApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body class="top-body">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to "タスク管理アプリ", root_path, class: "navbar-brand" %>     
    </nav>
    <div class="container">
      <!-- flashメッセージの表示 -->
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
        <%= yield %>
    </div>
    <div class="container-fluid">
    <footer class="footer">
      <p>Powered by Aguru Itabashi</p>
    </footer>
    </div>
  </body>
</html>